### ISSUE TITLE
panic: unable to fetch local commits

### ISSUE THREAD

**Issue by acabreragnz** [ejoffe/spr#104]
I replicates the readme example and I got this error, I generated two tokens just in case with repo scope, but the same error arises. 

```
panic: unable to fetch local commits

goroutine 1 [running]:
github.com/ejoffe/spr/spr.(*stackediff).getLocalCommitStack(0x90a6780, 0x83d0104, 0x29, 0x95c60f0)
        /Users/eitan/Code/spr/spr/spr.go:263 +0x213
github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests(0x90a6780, 0x8437fac, 0x901a0e0)
        /Users/eitan/Code/spr/spr/spr.go:89 +0xaa
main.main.func3(0x9097260, 0x2, 0x2)
        /Users/eitan/Code/spr/cmd/spr/main.go:139 +0x2e
github.com/urfave/cli/v2.(*Command).Run(0x90d1b00, 0x90971c0, 0x0, 0x0)
        /Users/eitan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x3c4
github.com/urfave/cli/v2.(*App).RunContext(0x9098680, 0x8437fac, 0x901a0e0, 0x910a000, 0x2, 0x2, 0x0, 0x0)
        /Users/eitan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x651
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/eitan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /Users/eitan/Code/spr/cmd/spr/main.go:174 +0xa26
```

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
git version 2.33.0

**Comment by ejoffe** [comment]
@acabreragnz - is it tomorrow yet? where you able to get it working?

**Comment by acabreragnz** [comment]
I'm sorry @ejoffe, lot of work from my side. I suppose is something in my machine let me close it, and I'll re-open it if it happens again.
