### ISSUE TITLE
Unable to handle branches with dots

### ISSUE THREAD

**Issue by sbienkow-ninja** [ejoffe/spr#177]
If a branch name has `.` character in it, SPR has weird behavior:

- Running `git spr update` first time, results in:
  ```sh
  $ git spr update
  > git rev-parse --show-toplevel
  > git status --porcelain
  > git remote -v
  pull request stack is empty
  ```
  The PR is created properly:
  ![image](https://user-images.githubusercontent.com/85104051/148241522-6f07efb1-738a-4654-8de3-9d5e908b6a79.png)

- Running `git spr status` results in:
  ```sh
  git spr status
  > git rev-parse --show-toplevel
  > git status --porcelain
  > git remote -v
  pull request stack is empty
  ```
- Running `git spr update` second time results in:
  ```sh
  git spr update
  > git rev-parse --show-toplevel
  > git status --porcelain
  > git remote -v
  panic: A pull request already exists for sbienkow-ninja:pr/sbienkow-ninja/branch.with.dots/677369d5.
  
  goroutine 1 [running]:
  github.com/ejoffe/spr/github/githubclient.check({0x8720a0, 0xc0000b4060})
	  /Users/runner/work/spr/spr/github/githubclient/client.go:542 +0xfa
  github.com/ejoffe/spr/github/githubclient.(*client).CreatePullRequest(0xc000312e30, {0x879e70, 0xc0000aa000}, 0xc0005520a0, {{0xc00021c0e1, 0x8}, {0xc00021c007, 0x28}, {0xc00021c098, 0x1c}, ...}, ...)
	  /Users/runner/work/spr/spr/github/githubclient/client.go:307 +0x5d5
  github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests(0xc000069080, {0x879e70, 0xc0000aa000})
	  /Users/runner/work/spr/spr/spr/spr.go:161 +0xa98
  main.main.func3(0xc0000bf5e0)
	  /Users/runner/work/spr/spr/cmd/spr/main.go:139 +0x25
  github.com/urfave/cli/v2.(*Command).Run(0xc0003145a0, 0xc00002ea00)
	  /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
  github.com/urfave/cli/v2.(*App).RunContext(0xc000001d40, {0x879e70, 0xc0000aa000}, {0xc0000be000, 0x2, 0x2})
	  /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
  github.com/urfave/cli/v2.(*App).Run(...)
	  /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
  main.main()
	  /Users/runner/work/spr/spr/cmd/spr/main.go:174 +0xde5
  ```
- Running `git spr merge` results in:
  ```sh
  git spr merge
  > git rev-parse --show-toplevel
  > git status --porcelain
  > git remote -v
  panic: A pull request already exists for sbienkow-ninja:pr/sbienkow-ninja/branch.with.dots/677369d5.
  
  goroutine 1 [running]:
  github.com/ejoffe/spr/github/githubclient.check({0x8720a0, 0xc000454150})
	  /Users/runner/work/spr/spr/github/githubclient/client.go:542 +0xfa
  github.com/ejoffe/spr/github/githubclient.(*client).CreatePullRequest(0xc0002c0010, {0x879e70, 0xc000118000}, 0xc000100f00, {{0xc0002b80e1, 0x8}, {0xc0002b8007, 0x28}, {0xc0002b8098, 0x1c}, ...}, ...)
	  /Users/runner/work/spr/spr/github/githubclient/client.go:307 +0x5d5
  github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests(0xc0000680c0, {0x879e70, 0xc000118000})
	  /Users/runner/work/spr/spr/spr/spr.go:161 +0xa98
  main.main.func4(0xc00012e4a0)
	  /Users/runner/work/spr/spr/cmd/spr/main.go:151 +0x48
  github.com/urfave/cli/v2.(*Command).Run(0xc0003ec240, 0xc0002c84c0)
	  /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
  github.com/urfave/cli/v2.(*App).RunContext(0xc000082d00, {0x879e70, 0xc000118000}, {0xc00012e000, 0x2, 0x2})
	  /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
  github.com/urfave/cli/v2.(*App).Run(...)
	  /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
  main.main()
	  /Users/runner/work/spr/spr/cmd/spr/main.go:174 +0xde5
  ```

**Comment by ejoffe** [comment]
fix released in v0.8.1
