### ISSUE TITLE
git error: fatal: cannot run /usr/bin/true: No such file or directory 

### ISSUE THREAD

**Issue by kilianyp** [ejoffe/spr#362]
When running `git amend` I am faced with the following error:

```
Commit to amend (1-2): 2
> git commit --fixup efa9629033b21c58fadb220f5add01e7a1124a30
> git rebase -i --autosquash --autostash origin/master
git error: fatal: cannot run /usr/bin/true: No such file or directory
error: unable to start editor '/usr/bin/true'
panic: exit status 1

goroutine 1 [running]:
github.com/ejoffe/spr/git/realgit.(*gitcmd).MustGit(0x7c6e34?, {0xc000034a80?, 0xc0000d3d00?}, 0x2?)
        /Users/runner/work/spr/spr/git/realgit/realcmd.go:44 +0x3c
github.com/ejoffe/spr/spr.(*stackediff).AmendCommit(0xc00007afc0, {0xa9ea40?, 0xc0000106c0?})
        /Users/runner/work/spr/spr/spr/spr.go:85 +0x586
main.main()
        /Users/runner/work/spr/spr/cmd/amend/main.go:66 +0x3af

```

I am on ubuntu:
```
git version 2.39.2
Release:        18.04
```

**Comment by kilianyp** [comment]
> git rebase -i --autosquash --autostash origin/master

That command still works fine in isolation, e.g. if I run `git commit --fixup..` and then `git rebase... ` manually.

**Comment by kilianyp** [comment]
I solved it by manually creating a `/bin/usr/true` that just echos 1.

I am using zsh, where `which true` returns `true: shell built-in command`.

**Comment by arbll** [comment]
Ran into the same issue, I'm also a `zsh` user

**Comment by schemar** [comment]
Same here. 

In https://github.com/ejoffe/spr/blob/0767a458e50fa1f7ae203b73e50298ab201c80bb/git/realgit/realcmd.go#L64
using `/usr/bin/env true` instead of `/usr/bin/true` would probably fix the issue for most users?

As a workaround, I symlinked my `true` to `/usr/bin/true`.
