### ISSUE TITLE
Can't rebase onto latest

### ISSUE THREAD

**Issue by b-chu** [ejoffe/spr#364]
There's no way to rebase stacked PRs onto the latest (or any) commit on main or dev.

**Comment by ejoffe** [comment]
Can you give more details?
`git spr update` will rebase your current stack on top of origin/main

**Comment by b-chu** [comment]
I get this stack trace when running that command
```
> git rev-parse --show-toplevel
> git fetch
> git rebase upstream/dev --autostash
> github fetch pull requests
> git log --format=medium --no-color upstream/dev..HEAD
> git branch --no-color
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b4d12]

goroutine 1 [running]:
github.com/ejoffe/spr/github/githubclient.(*client).GetInfo(0xc0000129c0, {0x9998f0?, 0xcc54c0?}, {0x999810, 0xc000012990})
        /root/spr/github/githubclient/client.go:199 +0x1f2
github.com/ejoffe/spr/spr.(*stackediff).fetchAndGetGitHubInfo(0xc000111020, {0x9998f0, 0xcc54c0})
        /root/spr/spr/spr.go:490 +0x164
github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests(0xc000111020, {0x9998f0?, 0xcc54c0}, {0x0, 0x0, 0x0}, 0x0)
        /root/spr/spr/spr.go:137 +0x97
main.main.func4(0xc000149400?)
        /root/spr/cmd/spr/main.go:155 +0x10f
github.com/urfave/cli/v2.(*Command).Run(0xc000308480, 0xc0000ff440)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x583
github.com/urfave/cli/v2.(*App).RunContext(0xc000224ea0, {0x9998f0?, 0xcc54c0}, {0xc000024120, 0x3, 0x3})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xaa5
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /root/spr/cmd/spr/main.go:224 +0x12db
```
