### ISSUE TITLE
git amend leads to panic when using pre-commit hooks

### ISSUE THREAD

**Issue by b1r3k** [ejoffe/spr#367]
git amend leads to panic when using pre-commit hooks

SPR VERSION: fork of 0.14.4 : 2023-10-19T22:50:47Z : ca55507b
git version 2.40.1

```bash
Commit to amend (1-6): 5
> git commit --fixup 74ab3da0f64675cc6a64d985c31f325e30f2f324
git error: Trim Trailing Whitespace.............................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Check for added large files..........................(no files to check)Skipped
black................................................(no files to check)Skipped
isort (python).......................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
On branch master
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
panic: exit status 1

goroutine 1 [running]:
github.com/ejoffe/spr/git/realgit.(*gitcmd).MustGit(0x0?, {0xc000228cc0?, 0x7becf2?}, 0xc0002961ab?)
	/Users/runner/work/spr/spr/git/realgit/realcmd.go:44 +0x3c
github.com/ejoffe/spr/spr.(*stackediff).AmendCommit(0xc0002647e0, {0xa9ea40?, 0xc000010678?})
	/Users/runner/work/spr/spr/spr/spr.go:81 +0x4d1
main.main()
	/Users/runner/work/spr/spr/cmd/amend/main.go:66 +0x3af
```

**Comment by b1r3k** [comment]
need to reproduce again
