### ISSUE TITLE
GitHub star on Enterprise

### ISSUE THREAD

**Issue by piefel** [ejoffe/spr#386]
Since I’m on a Github Enterprise server, the star redirect fails with a stack trace:

> enjoying git spr? add a GitHub star? [Y/n]:
> panic: repository: Could not resolve to a Repository with the name 'ejoffe/spr'.
> […]

**Comment by ejoffe** [comment]
What version of spr are you using?

**Comment by piefel** [comment]
Don’t have access to _that_ machine now, but it has been freshly updated a few days ago, so it should be 0.14.8

**Comment by ejoffe** [comment]
There was a recent bug fix in this released in 0.14.8 on 1/12/2024. 
If you are running a previous version, this is a known issue. 
If you are really running 0.14.8, then the issue still exists post fix.

**Comment by piefel** [comment]
```
$ git spr status
> git rev-parse --show-toplevel
enjoying git spr? add a GitHub star? [Y/n]:
panic: repository: Could not resolve to a Repository with the name 'ejoffe/spr'.


goroutine 1 [running]:
github.com/ejoffe/spr/github/githubclient.check({0x995c20, 0xc0004078a8})
	/Users/runner/work/spr/spr/github/githubclient/client.go:696 +0xf4
github.com/ejoffe/spr/github/githubclient.(*client).addStar(0xc0000b2990, {0x999390, 0xcc85c0})
	/Users/runner/work/spr/spr/github/githubclient/star.go:100 +0x5b
github.com/ejoffe/spr/github/githubclient.(*client).MaybeStar(0xc0000bb340?, {0x999390, 0xcc85c0}, 0xc0000b2738)
	/Users/runner/work/spr/spr/github/githubclient/star.go:53 +0x609
main.main.func1(0xc0000ed100?)
	/Users/runner/work/spr/spr/cmd/spr/main.go:125 +0x1a5
github.com/urfave/cli/v2.(*App).RunContext(0xc000093ba0, {0x999390?, 0xcc85c0}, {0xc0000bc000, 0x2, 0x2})
	/Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:328 +0x722
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
main.main()
	/Users/runner/work/spr/spr/cmd/spr/main.go:230 +0x133b
```

---

```
AUTHOR: Eitan Joffe <eitan@inigolabs.com>
VERSION: fork of 0.14.8 : 2024-01-12T00:36:25Z : c43d4c16
```
