### ISSUE TITLE
Crash during spr status call ( 0.14.9 )

### ISSUE THREAD

**Issue by steinemann** [ejoffe/spr#419]
Hi,

When starting `git spr` I got this crash:
```
>> git spr s
rake: config file /data/d058808/dev/cloudstore/.spr.yml not found
> git rev-parse --show-toplevel
> github fetch pull requests
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b3f8e]

goroutine 1 [running]:
github.com/ejoffe/spr/github/githubclient.(*client).GetInfo(0xc000010930, {0x999490?, 0xcc9660?}, {0x9993b0, 0xc000010900})
        /Users/runner/work/spr/spr/github/githubclient/client.go:200 +0x14e
github.com/ejoffe/spr/spr.(*stackediff).StatusPullRequests(0xc0000d1080, {0x999490, 0xcc9660})
        /Users/runner/work/spr/spr/spr/spr.go:349 +0x6a
main.main.func2(0xc000242d80?)
        /Users/runner/work/spr/spr/cmd/spr/main.go:134 +0x1f
github.com/urfave/cli/v2.(*Command).Run(0xc000242d80, 0xc0000f53c0)
        /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x5eb
github.com/urfave/cli/v2.(*App).RunContext(0xc00020a820, {0x999490?, 0xcc9660}, {0xc000022040, 0x2, 0x2})
        /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xb05
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
main.main()
        /Users/runner/work/spr/spr/cmd/spr/main.go:230 +0x133b
```

```
 >> git-spr version
> git rev-parse --show-toplevel
0.14.9 : 2024-03-15T19:34:25Z : e2eb7866
````

Any idea why it did not work for me ?

Thanks,
Peter

**Comment by steinemann** [comment]
For those running into the same issue:

You need to login to your github first using `gh auth login`
