### ISSUE TITLE
SIGSEGV running git spr update -c 1

### ISSUE THREAD

**Issue by yang** [ejoffe/spr#420]
It's updating an existing PR.

```
$ git spr update -c 1
...
> github update 45455 : Do stuff
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102fd6b58]

goroutine 35 [running]:
github.com/ejoffe/spr/github/githubclient.formatStackMarkdown({{0x140000aa1a1, 0x8}, {0x140000aa0df, 0x28}, {0x140000aa167, 0x26}, {0x1030df080, 0x0}, 0x0}, {0x140002eb940, ...}, ...)
	/Users/runner/work/spr/spr/github/githubclient/client.go:431 +0x128
github.com/ejoffe/spr/github/githubclient.formatBody({{0x140000aa1a1, 0x8}, {0x140000aa0df, 0x28}, {0x140000aa167, 0x26}, {0x1030df080, 0x0}, 0x0}, {0x140002eb940?, ...}, ...)
	/Users/runner/work/spr/spr/github/githubclient/client.go:458 +0x74
github.com/ejoffe/spr/github/githubclient.(*client).UpdatePullRequest(0x1400000ca68, {0x1031c04f0, 0x1034dd500}, {0x1031c0410, 0x1400000ca38}, {0x140002eb940, 0x2, 0x2}, 0x14000355a40, {{0x140000aa1a1, ...}, ...}, ...)
	/Users/runner/work/spr/spr/github/githubclient/client.go:549 +0x340
github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests.func2(0x140001b8a80?)
	/Users/runner/work/spr/spr/spr/spr.go:242 +0xcc
created by github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests in goroutine 1
	/Users/runner/work/spr/spr/spr/spr.go:240 +0x108c
```

Dropping the `-c 1` has no issue.

```
VERSION: fork of 0.14.9 : 2024-03-15T19:34:25Z : e2eb7866
```

**Comment by chriscz** [comment]
Ran into the same issue now. I will try to have a look this weekend.
